# Generated by Django 4.1.1 on 2025-03-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_quantity_payment_cart_order_payment'),
        ('product', '0003_product_quantity_payment_order_payment'),
        ('product', '0004_payment_order_payment'),
    ]

    operations = [
    ]
